name: Add Version Comment

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]
  # trigger deployment manually
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Modify version worker-vless.js
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: src/worker-vless.js
          body: "version base on commit ${{ github.sha }}, time is {{date:YYYY-MM-DD HH:mm:ss}} UTC"
          message: "Update version worker-vless.js"
